In [9]:
import tensorflow as tf

In [10]:
import numpy as np

many_ones = np.ones([3, 3])

In [11]:
tensor = tf.multiply(many_ones, 42)
print(tensor)

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
