[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/eirasf/GCED-AA2/blob/main/lab1/4_Numpy.ipynb)

In [ ]:
import tensorflow as tf

In [ ]:
import numpy as np

many_ones = np.ones([3, 3])

In [ ]:
tensor = tf.multiply(many_ones, 42)
print(tensor)

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
